### ISSUE TITLE
[1.2.x] Method `KiriminAja::getPriceInstant` API URL not found

### ISSUE THREAD

**Issue by vozaldi** [kiriminaja/php#27]
Halo, thank you for the update 🎉

Today I tried the new method `KiriminAja::getPriceInstant($payload)` as shown in KiriminAja Docs. But when I execute the code, it returns a message "Unable to find your endpoint target".

``` PHP
$payload = new ShippingPriceInstantData();
$payload->weight = 1000;
$payload->origin_address = "My address here";
$payload->origin_long = 109.721648;
$payload->origin_lat = -7.548291;
$payload->destination_address = "Customer address here";
$payload->destination_long = 110.81489630422;
$payload->destination_lat = -7.5616587725195;
$payload->item_price = 100000;

$prices = KiriminAja::getPriceInstant($payload);
```

I also tried the API using manual POST method in Postman and it worked.

`[POST] https://apieks-staging.kiriminaja.com/open-api/v1/instants/price`

---

### Found Bug

The API URL in method `KiriminAja::getPriceInstant(...)` is resulting this value:

`https://tdev.kiriminaja.com/open-api/v1/instants/price`

Which cannot be accessed and returning a message "Unable to find your endpoint target".

And this is what I think is the root cause, method `self::url(...)` will never return `self::baseURLInstant()`

https://github.com/kiriminaja/php/blob/bf7a896151104842de5f18746ced3920511d8c0e/src/Base/Api/ApiOptions.php#L111-L115

---

I hope you can solve this issue. Thank you.

**Comment by yanuaraditia** [comment]
Thanks for reporting, we'll fix this immediately
